class TransactionPool:
    def __init__(self):
        self.transaction_store = {}
        
    def set_transaction(self, transaction):
        """
        Set a transaction in the transaction pool
        """
        self.transaction_store[transaction.id] = transaction
    
    def existing_transaction(self, address):
        """
        Finds a transaction generated by the address in the transaction pool
        """
        for transaction in self.transaction_store.values():
            if transaction.input['address'] ==  address:
                return transaction
    def transaction_data(self):
        """
        Return the transaction data in the transaction store as a json
        """
        return list(
            map(lambda trans: trans.serializer(),
                self.transaction_store.values()))
    
    def clear_blockchain_transaction(self,blockchain):
        """
        Deletes chain recored transcations fron teh transaction store
        """       
        for blocks in blockchain.chain:
            for transaction in blocks.data:
                try:
                    del self.transaction_store[transaction['id']]
                except KeyError:
                    pass